/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:e9c872ec-2949-4013-9e71-d8f811603928",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_G7H0uIJDx",
    "aws_user_pools_web_client_id": "35nvsj61b0v4hs6kj2leeb3lrg",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tdztvksj6rd7zjmpgyxdnfcvla.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
